on: 
  push:
    branches:
      - "main"

name: Deploy to foobatree main website
jobs:
  web-deploy:
    name: deploy thumbsup
    runs-on: ubuntu-latest
    steps:
    - name: idk man
      uses: actions/checkout@v4
    
    - name: Sync da files 🔥🔥🔥
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_37638961
        password: ${{ secrets.password }}
        server-dir: ./htdocs/
